In [1]:
import itertools
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

# data for flow 80

In [6]:
pin_positions = list(range(10))
pin_combinations=[position for position in itertools.combinations_with_replacement(pin_positions, 2)]
pin_combinations

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 8),
 (8, 9),
 (9, 9)]

In [7]:
flow_rate = 80
def flow_division(range_of_difference):
  pos_1= flow_rate*0.7
  pos_2= flow_rate*0.3
  for diff in range(range_of_difference):
    diff_value=(pos_1-pos_2)/10
    pos_1=pos_1-diff_value
    pos_2=pos_2+diff_value
  return (pos_1/24,pos_2/24)

In [ ]:
velocity_lst=[]
flow_lst=[abs]
for pair in pin_combinations:
  if pair[0]>pair[1]:
    range_is=9-pair[0]+pair[1]
    pos_1,pos_2=flow_division(range_is)
    velocity_lst.append([pair[0],pair[0],pair[1],pair[1], pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2, pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2, 
                pos_2+0.25,pos_2-0.3])   
    flow_lst.append([pair[0],pair[0],pair[1],pair[1],x*12,x*12,pos_2*12,pos_2*12])
  elif pair[0]==pair[1]:
    range_is=9
    x,y=flow_division(range_is)
    velocity_lst.append([pair[0],pair[0],pair[1],pair[1],pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2, 
                pos_2+0.25,pos_2-0.3])
    flow_lst.append([pair[0],pair[0],pair[1],pair[1],20,20,20,20])

  else:
    range_is=9-pair[1]+pair[0]
    y,x=flow_division(range_is)
    velocity_lst.append([pair[1],pair[1],pair[0],pair[0], pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2, 
                pos_1+0.25,pos_1-0.3])                                                  
    flow_lst.append([pair[1],pair[1],pair[0],pair[0],pos_2*12,pos_2*12,pos_1*12,pos_1*12])

In [ ]:
df=pd.DataFrame(velocity_lst)
df.columns=['pin1','pin2','pin3','pin4','v1','v2','v3','v4','v5','v6','v7','v8','v9','v10','v11','v12','v13','v14','v15','v16']
df=df.round(3)
df

    pin1  pin2  pin3  pin4     v1  ...    v12    v13    v14    v15    v16
0      1     1     1     1  1.827  ...  1.456  2.006  1.556  1.827  1.277
1      2     2     1     1  1.805  ...  1.479  2.029  1.579  1.805  1.255
2      3     3     1     1  1.777  ...  1.506  2.056  1.606  1.777  1.227
3      4     4     1     1  1.742  ...  1.541  2.091  1.641  1.742  1.192
4      5     5     1     1  1.698  ...  1.585  2.135  1.685  1.698  1.148
5      6     6     1     1  1.644  ...  1.640  2.190  1.740  1.644  1.094
6      7     7     1     1  1.575  ...  1.708  2.258  1.808  1.575  1.025
7      8     8     1     1  1.490  ...  1.793  2.343  1.893  1.490  0.940
8      9     9     1     1  1.383  ...  1.900  2.450  2.000  1.383  0.833
9      1     1     0     0  1.805  ...  1.479  2.029  1.579  1.805  1.255
10     2     2     2     2  1.827  ...  1.456  2.006  1.556  1.827  1.277
11     3     3     2     2  1.805  ...  1.479  2.029  1.579  1.805  1.255
12     4     4     2     2  1.777  ...  1.506  2.056  1.606  1.777  1.227
13     5     5     2     2  1.742  ...  1.541  2.091  1.641  1.742  1.192
14     6     6     2     2  1.698  ...  1.585  2.135  1.685  1.698  1.148
15     7     7     2     2  1.644  ...  1.640  2.190  1.740  1.644  1.094
16     8     8     2     2  1.575  ...  1.708  2.258  1.808  1.575  1.025
17     9     9     2     2  1.490  ...  1.793  2.343  1.893  1.490  0.940
18     2     2     0     0  1.777  ...  1.506  2.056  1.606  1.777  1.227
19     3     3     3     3  1.827  ...  1.456  2.006  1.556  1.827  1.277
20     4     4     3     3  1.805  ...  1.479  2.029  1.579  1.805  1.255
21     5     5     3     3  1.777  ...  1.506  2.056  1.606  1.777  1.227
22     6     6     3     3  1.742  ...  1.541  2.091  1.641  1.742  1.192
23     7     7     3     3  1.698  ...  1.585  2.135  1.685  1.698  1.148
24     8     8     3     3  1.644  ...  1.640  2.190  1.740  1.644  1.094
25     9     9     3     3  1.575  ...  1.708  2.258  1.808  1.575  1.025
26     3     3     0     0  1.742  ...  1.541  2.091  1.641  1.742  1.192
27     4     4     4     4  1.827  ...  1.456  2.006  1.556  1.827  1.277
28     5     5     4     4  1.805  ...  1.479  2.029  1.579  1.805  1.255
29     6     6     4     4  1.777  ...  1.506  2.056  1.606  1.777  1.227
30     7     7     4     4  1.742  ...  1.541  2.091  1.641  1.742  1.192
31     8     8     4     4  1.698  ...  1.585  2.135  1.685  1.698  1.148
32     9     9     4     4  1.644  ...  1.640  2.190  1.740  1.644  1.094
33     4     4     0     0  1.698  ...  1.585  2.135  1.685  1.698  1.148
34     5     5     5     5  1.827  ...  1.456  2.006  1.556  1.827  1.277
35     6     6     5     5  1.805  ...  1.479  2.029  1.579  1.805  1.255
36     7     7     5     5  1.777  ...  1.506  2.056  1.606  1.777  1.227
37     8     8     5     5  1.742  ...  1.541  2.091  1.641  1.742  1.192
38     9     9     5     5  1.698  ...  1.585  2.135  1.685  1.698  1.148
39     5     5     0     0  1.644  ...  1.640  2.190  1.740  1.644  1.094
40     6     6     6     6  1.827  ...  1.456  2.006  1.556  1.827  1.277
41     7     7     6     6  1.805  ...  1.479  2.029  1.579  1.805  1.255
42     8     8     6     6  1.777  ...  1.506  2.056  1.606  1.777  1.227
43     9     9     6     6  1.742  ...  1.541  2.091  1.641  1.742  1.192
44     6     6     0     0  1.575  ...  1.708  2.258  1.808  1.575  1.025
45     7     7     7     7  1.827  ...  1.456  2.006  1.556  1.827  1.277
46     8     8     7     7  1.805  ...  1.479  2.029  1.579  1.805  1.255
47     9     9     7     7  1.777  ...  1.506  2.056  1.606  1.777  1.227
48     7     7     0     0  1.490  ...  1.793  2.343  1.893  1.490  0.940
49     8     8     8     8  1.827  ...  1.456  2.006  1.556  1.827  1.277
50     9     9     8     8  1.805  ...  1.479  2.029  1.579  1.805  1.255
51     8     8     0     0  1.383  ...  1.900  2.450  2.000  1.383  0.833
52     9     9     9     9  1.827  ...  1.456  2.006  1.556  1.827  1.277
53     9     9     0     0  1.250  ...  2.033  2.583  2.133  1.250  0.700
54     0     0     0     0  1.827  ...  1.456  2.006  1.556  1.827  1.277

[55 rows x 20 columns]

In [ ]:
flow_lst.remove(flow_lst[0])

In [ ]:
df2=pd.DataFrame(flow_lst)
df2=df2.round(3)
df2.columns=['pin1','pin2','pin3','pin4','flow1','flow2','flow3','flow4']
df2

    pin1  pin2  pin3  pin4   flow1   flow2   flow3   flow4
0      1     1     1     1  20.000  20.000  20.000  20.000
1      2     2     1     1  21.342  21.342  18.658  18.658
2      3     3     1     1  21.678  21.678  18.322  18.322
3      4     4     1     1  22.097  22.097  17.903  17.903
4      5     5     1     1  22.621  22.621  17.379  17.379
5      6     6     1     1  23.277  23.277  16.723  16.723
6      7     7     1     1  24.096  24.096  15.904  15.904
7      8     8     1     1  25.120  25.120  14.880  14.880
8      9     9     1     1  26.400  26.400  13.600  13.600
9      1     1     0     0  21.342  21.342  18.658  18.658
10     2     2     2     2  20.000  20.000  20.000  20.000
11     3     3     2     2  21.342  21.342  18.658  18.658
12     4     4     2     2  21.678  21.678  18.322  18.322
13     5     5     2     2  22.097  22.097  17.903  17.903
14     6     6     2     2  22.621  22.621  17.379  17.379
15     7     7     2     2  23.277  23.277  16.723  16.723
16     8     8     2     2  24.096  24.096  15.904  15.904
17     9     9     2     2  25.120  25.120  14.880  14.880
18     2     2     0     0  21.678  21.678  18.322  18.322
19     3     3     3     3  20.000  20.000  20.000  20.000
20     4     4     3     3  21.342  21.342  18.658  18.658
21     5     5     3     3  21.678  21.678  18.322  18.322
22     6     6     3     3  22.097  22.097  17.903  17.903
23     7     7     3     3  22.621  22.621  17.379  17.379
24     8     8     3     3  23.277  23.277  16.723  16.723
25     9     9     3     3  24.096  24.096  15.904  15.904
26     3     3     0     0  22.097  22.097  17.903  17.903
27     4     4     4     4  20.000  20.000  20.000  20.000
28     5     5     4     4  21.342  21.342  18.658  18.658
29     6     6     4     4  21.678  21.678  18.322  18.322
30     7     7     4     4  22.097  22.097  17.903  17.903
31     8     8     4     4  22.621  22.621  17.379  17.379
32     9     9     4     4  23.277  23.277  16.723  16.723
33     4     4     0     0  22.621  22.621  17.379  17.379
34     5     5     5     5  20.000  20.000  20.000  20.000
35     6     6     5     5  21.342  21.342  18.658  18.658
36     7     7     5     5  21.678  21.678  18.322  18.322
37     8     8     5     5  22.097  22.097  17.903  17.903
38     9     9     5     5  22.621  22.621  17.379  17.379
39     5     5     0     0  23.277  23.277  16.723  16.723
40     6     6     6     6  20.000  20.000  20.000  20.000
41     7     7     6     6  21.342  21.342  18.658  18.658
42     8     8     6     6  21.678  21.678  18.322  18.322
43     9     9     6     6  22.097  22.097  17.903  17.903
44     6     6     0     0  24.096  24.096  15.904  15.904
45     7     7     7     7  20.000  20.000  20.000  20.000
46     8     8     7     7  21.342  21.342  18.658  18.658
47     9     9     7     7  21.678  21.678  18.322  18.322
48     7     7     0     0  25.120  25.120  14.880  14.880
49     8     8     8     8  20.000  20.000  20.000  20.000
50     9     9     8     8  21.342  21.342  18.658  18.658
51     8     8     0     0  26.400  26.400  13.600  13.600
52     9     9     9     9  20.000  20.000  20.000  20.000
53     9     9     0     0  28.000  28.000  12.000  12.000
54     0     0     0     0  20.000  20.000  20.000  20.000

In [ ]:
df2['flow1']=(((df2['flow1'])/(df2['flow1']+df2['flow4']))*100)/2
df2['flow4']=(((df2['flow3'])/(df2['flow2']+df2['flow3']))*100)/2
df2['flow2']=df2['flow1']
df2['flow3']=df2['flow4']
df2

    pin1  pin2  pin3  pin4     flow1     flow2     flow3     flow4
0      1     1     1     1  25.00000  25.00000  25.00000  25.00000
1      2     2     1     1  26.67750  26.67750  23.32250  23.32250
2      3     3     1     1  27.09750  27.09750  22.90250  22.90250
3      4     4     1     1  27.62125  27.62125  22.37875  22.37875
4      5     5     1     1  28.27625  28.27625  21.72375  21.72375
5      6     6     1     1  29.09625  29.09625  20.90375  20.90375
6      7     7     1     1  30.12000  30.12000  19.88000  19.88000
7      8     8     1     1  31.40000  31.40000  18.60000  18.60000
8      9     9     1     1  33.00000  33.00000  17.00000  17.00000
9      1     1     0     0  26.67750  26.67750  23.32250  23.32250
10     2     2     2     2  25.00000  25.00000  25.00000  25.00000
11     3     3     2     2  26.67750  26.67750  23.32250  23.32250
12     4     4     2     2  27.09750  27.09750  22.90250  22.90250
13     5     5     2     2  27.62125  27.62125  22.37875  22.37875
14     6     6     2     2  28.27625  28.27625  21.72375  21.72375
15     7     7     2     2  29.09625  29.09625  20.90375  20.90375
16     8     8     2     2  30.12000  30.12000  19.88000  19.88000
17     9     9     2     2  31.40000  31.40000  18.60000  18.60000
18     2     2     0     0  27.09750  27.09750  22.90250  22.90250
19     3     3     3     3  25.00000  25.00000  25.00000  25.00000
20     4     4     3     3  26.67750  26.67750  23.32250  23.32250
21     5     5     3     3  27.09750  27.09750  22.90250  22.90250
22     6     6     3     3  27.62125  27.62125  22.37875  22.37875
23     7     7     3     3  28.27625  28.27625  21.72375  21.72375
24     8     8     3     3  29.09625  29.09625  20.90375  20.90375
25     9     9     3     3  30.12000  30.12000  19.88000  19.88000
26     3     3     0     0  27.62125  27.62125  22.37875  22.37875
27     4     4     4     4  25.00000  25.00000  25.00000  25.00000
28     5     5     4     4  26.67750  26.67750  23.32250  23.32250
29     6     6     4     4  27.09750  27.09750  22.90250  22.90250
30     7     7     4     4  27.62125  27.62125  22.37875  22.37875
31     8     8     4     4  28.27625  28.27625  21.72375  21.72375
32     9     9     4     4  29.09625  29.09625  20.90375  20.90375
33     4     4     0     0  28.27625  28.27625  21.72375  21.72375
34     5     5     5     5  25.00000  25.00000  25.00000  25.00000
35     6     6     5     5  26.67750  26.67750  23.32250  23.32250
36     7     7     5     5  27.09750  27.09750  22.90250  22.90250
37     8     8     5     5  27.62125  27.62125  22.37875  22.37875
38     9     9     5     5  28.27625  28.27625  21.72375  21.72375
39     5     5     0     0  29.09625  29.09625  20.90375  20.90375
40     6     6     6     6  25.00000  25.00000  25.00000  25.00000
41     7     7     6     6  26.67750  26.67750  23.32250  23.32250
42     8     8     6     6  27.09750  27.09750  22.90250  22.90250
43     9     9     6     6  27.62125  27.62125  22.37875  22.37875
44     6     6     0     0  30.12000  30.12000  19.88000  19.88000
45     7     7     7     7  25.00000  25.00000  25.00000  25.00000
46     8     8     7     7  26.67750  26.67750  23.32250  23.32250
47     9     9     7     7  27.09750  27.09750  22.90250  22.90250
48     7     7     0     0  31.40000  31.40000  18.60000  18.60000
49     8     8     8     8  25.00000  25.00000  25.00000  25.00000
50     9     9     8     8  26.67750  26.67750  23.32250  23.32250
51     8     8     0     0  33.00000  33.00000  17.00000  17.00000
52     9     9     9     9  25.00000  25.00000  25.00000  25.00000
53     9     9     0     0  35.00000  35.00000  15.00000  15.00000
54     0     0     0     0  25.00000  25.00000  25.00000  25.00000

# data for flow 50

In [8]:
pin_positions = list(range(10))
pin_combinations=[position for position in itertools.combinations_with_replacement(pin_positions, 2)]
pin_combinations

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 8),
 (8, 9),
 (9, 9)]

In [ ]:
flow_rate = 50
def flow_division(range_of_difference):
  pos_1= flow_rate*0.7
  pos_2= flow_rate*0.3
  for diff in range(range_of_difference):
    diff_value=(pos_1-pos_2)/10
    pos_1=pos_1-diff_value
    pos_2=pos_2+diff_value
  return (pos_1/24,pos_2/24)

In [ ]:
velocity_lst=[]
flow_lst=[abs]
for pair in pin_combinations:
  if pair[0]>pair[1]:
    range_is=9-pair[0]+pair[1]
    pos_1,pos_2=flow_division(range_is)
    velocity_lst.append([pair[0],pair[0],pair[1],pair[1], pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2, pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2, 
                pos_2+0.25,pos_2-0.3])   
    flow_lst.append([pair[0],pair[0],pair[1],pair[1],x*12,x*12,pos_2*12,pos_2*12])
  elif pair[0]==pair[1]:
    range_is=9
    x,y=flow_division(range_is)
    velocity_lst.append([pair[0],pair[0],pair[1],pair[1],pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2, 
                pos_2+0.25,pos_2-0.3])
    flow_lst.append([pair[0],pair[0],pair[1],pair[1],20,20,20,20])

  else:
    range_is=9-pair[1]+pair[0]
    y,x=flow_division(range_is)
    velocity_lst.append([pair[1],pair[1],pair[0],pair[0], pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2, 
                pos_1+0.25,pos_1-0.3])                                                  
    flow_lst.append([pair[1],pair[1],pair[0],pair[0],pos_2*12,pos_2*12,pos_1*12,pos_1*12])

In [ ]:
df=pd.DataFrame(velocity_lst)
df.columns=['pin1','pin2','pin3','pin4','v1','v2','v3','v4','v5','v6','v7','v8','v9','v10','v11','v12','v13','v14','v15','v16']
df=df.round(3)
df

    pin1  pin2  pin3  pin4     v1  ...    v12    v13    v14    v15    v16
0      1     1     1     1  1.236  ...  0.798  1.348  0.898  1.236  0.686
1      2     2     1     1  1.222  ...  0.812  1.362  0.912  1.222  0.672
2      3     3     1     1  1.204  ...  0.829  1.379  0.929  1.204  0.654
3      4     4     1     1  1.182  ...  0.851  1.401  0.951  1.182  0.632
4      5     5     1     1  1.155  ...  0.878  1.428  0.978  1.155  0.605
5      6     6     1     1  1.121  ...  0.912  1.462  1.012  1.121  0.571
6      7     7     1     1  1.078  ...  0.955  1.505  1.055  1.078  0.528
7      8     8     1     1  1.025  ...  1.008  1.558  1.108  1.025  0.475
8      9     9     1     1  0.958  ...  1.075  1.625  1.175  0.958  0.408
9      1     1     0     0  1.222  ...  0.812  1.362  0.912  1.222  0.672
10     2     2     2     2  1.236  ...  0.798  1.348  0.898  1.236  0.686
11     3     3     2     2  1.222  ...  0.812  1.362  0.912  1.222  0.672
12     4     4     2     2  1.204  ...  0.829  1.379  0.929  1.204  0.654
13     5     5     2     2  1.182  ...  0.851  1.401  0.951  1.182  0.632
14     6     6     2     2  1.155  ...  0.878  1.428  0.978  1.155  0.605
15     7     7     2     2  1.121  ...  0.912  1.462  1.012  1.121  0.571
16     8     8     2     2  1.078  ...  0.955  1.505  1.055  1.078  0.528
17     9     9     2     2  1.025  ...  1.008  1.558  1.108  1.025  0.475
18     2     2     0     0  1.204  ...  0.829  1.379  0.929  1.204  0.654
19     3     3     3     3  1.236  ...  0.798  1.348  0.898  1.236  0.686
20     4     4     3     3  1.222  ...  0.812  1.362  0.912  1.222  0.672
21     5     5     3     3  1.204  ...  0.829  1.379  0.929  1.204  0.654
22     6     6     3     3  1.182  ...  0.851  1.401  0.951  1.182  0.632
23     7     7     3     3  1.155  ...  0.878  1.428  0.978  1.155  0.605
24     8     8     3     3  1.121  ...  0.912  1.462  1.012  1.121  0.571
25     9     9     3     3  1.078  ...  0.955  1.505  1.055  1.078  0.528
26     3     3     0     0  1.182  ...  0.851  1.401  0.951  1.182  0.632
27     4     4     4     4  1.236  ...  0.798  1.348  0.898  1.236  0.686
28     5     5     4     4  1.222  ...  0.812  1.362  0.912  1.222  0.672
29     6     6     4     4  1.204  ...  0.829  1.379  0.929  1.204  0.654
30     7     7     4     4  1.182  ...  0.851  1.401  0.951  1.182  0.632
31     8     8     4     4  1.155  ...  0.878  1.428  0.978  1.155  0.605
32     9     9     4     4  1.121  ...  0.912  1.462  1.012  1.121  0.571
33     4     4     0     0  1.155  ...  0.878  1.428  0.978  1.155  0.605
34     5     5     5     5  1.236  ...  0.798  1.348  0.898  1.236  0.686
35     6     6     5     5  1.222  ...  0.812  1.362  0.912  1.222  0.672
36     7     7     5     5  1.204  ...  0.829  1.379  0.929  1.204  0.654
37     8     8     5     5  1.182  ...  0.851  1.401  0.951  1.182  0.632
38     9     9     5     5  1.155  ...  0.878  1.428  0.978  1.155  0.605
39     5     5     0     0  1.121  ...  0.912  1.462  1.012  1.121  0.571
40     6     6     6     6  1.236  ...  0.798  1.348  0.898  1.236  0.686
41     7     7     6     6  1.222  ...  0.812  1.362  0.912  1.222  0.672
42     8     8     6     6  1.204  ...  0.829  1.379  0.929  1.204  0.654
43     9     9     6     6  1.182  ...  0.851  1.401  0.951  1.182  0.632
44     6     6     0     0  1.078  ...  0.955  1.505  1.055  1.078  0.528
45     7     7     7     7  1.236  ...  0.798  1.348  0.898  1.236  0.686
46     8     8     7     7  1.222  ...  0.812  1.362  0.912  1.222  0.672
47     9     9     7     7  1.204  ...  0.829  1.379  0.929  1.204  0.654
48     7     7     0     0  1.025  ...  1.008  1.558  1.108  1.025  0.475
49     8     8     8     8  1.236  ...  0.798  1.348  0.898  1.236  0.686
50     9     9     8     8  1.222  ...  0.812  1.362  0.912  1.222  0.672
51     8     8     0     0  0.958  ...  1.075  1.625  1.175  0.958  0.408
52     9     9     9     9  1.236  ...  0.798  1.348  0.898  1.236  0.686
53     9     9     0     0  0.875  ...  1.158  1.708  1.258  0.875  0.325
54     0     0     0     0  1.236  ...  0.798  1.348  0.898  1.236  0.686

[55 rows x 20 columns]

In [ ]:
flow_lst.remove(flow_lst[0])

In [ ]:
df2=pd.DataFrame(flow_lst)
df2=df2.round(3)
df2.columns=['pin1','pin2','pin3','pin4','flow1','flow2','flow3','flow4']
df2

    pin1  pin2  pin3  pin4   flow1   flow2   flow3   flow4
0      1     1     1     1  12.500  12.500  12.500  12.500
1      2     2     1     1  13.339  13.339  11.661  11.661
2      3     3     1     1  13.549  13.549  11.451  11.451
3      4     4     1     1  13.811  13.811  11.189  11.189
4      5     5     1     1  14.138  14.138  10.862  10.862
5      6     6     1     1  14.548  14.548  10.452  10.452
6      7     7     1     1  15.060  15.060   9.940   9.940
7      8     8     1     1  15.700  15.700   9.300   9.300
8      9     9     1     1  16.500  16.500   8.500   8.500
9      1     1     0     0  13.339  13.339  11.661  11.661
10     2     2     2     2  12.500  12.500  12.500  12.500
11     3     3     2     2  13.339  13.339  11.661  11.661
12     4     4     2     2  13.549  13.549  11.451  11.451
13     5     5     2     2  13.811  13.811  11.189  11.189
14     6     6     2     2  14.138  14.138  10.862  10.862
15     7     7     2     2  14.548  14.548  10.452  10.452
16     8     8     2     2  15.060  15.060   9.940   9.940
17     9     9     2     2  15.700  15.700   9.300   9.300
18     2     2     0     0  13.549  13.549  11.451  11.451
19     3     3     3     3  12.500  12.500  12.500  12.500
20     4     4     3     3  13.339  13.339  11.661  11.661
21     5     5     3     3  13.549  13.549  11.451  11.451
22     6     6     3     3  13.811  13.811  11.189  11.189
23     7     7     3     3  14.138  14.138  10.862  10.862
24     8     8     3     3  14.548  14.548  10.452  10.452
25     9     9     3     3  15.060  15.060   9.940   9.940
26     3     3     0     0  13.811  13.811  11.189  11.189
27     4     4     4     4  12.500  12.500  12.500  12.500
28     5     5     4     4  13.339  13.339  11.661  11.661
29     6     6     4     4  13.549  13.549  11.451  11.451
30     7     7     4     4  13.811  13.811  11.189  11.189
31     8     8     4     4  14.138  14.138  10.862  10.862
32     9     9     4     4  14.548  14.548  10.452  10.452
33     4     4     0     0  14.138  14.138  10.862  10.862
34     5     5     5     5  12.500  12.500  12.500  12.500
35     6     6     5     5  13.339  13.339  11.661  11.661
36     7     7     5     5  13.549  13.549  11.451  11.451
37     8     8     5     5  13.811  13.811  11.189  11.189
38     9     9     5     5  14.138  14.138  10.862  10.862
39     5     5     0     0  14.548  14.548  10.452  10.452
40     6     6     6     6  12.500  12.500  12.500  12.500
41     7     7     6     6  13.339  13.339  11.661  11.661
42     8     8     6     6  13.549  13.549  11.451  11.451
43     9     9     6     6  13.811  13.811  11.189  11.189
44     6     6     0     0  15.060  15.060   9.940   9.940
45     7     7     7     7  12.500  12.500  12.500  12.500
46     8     8     7     7  13.339  13.339  11.661  11.661
47     9     9     7     7  13.549  13.549  11.451  11.451
48     7     7     0     0  15.700  15.700   9.300   9.300
49     8     8     8     8  12.500  12.500  12.500  12.500
50     9     9     8     8  13.339  13.339  11.661  11.661
51     8     8     0     0  16.500  16.500   8.500   8.500
52     9     9     9     9  12.500  12.500  12.500  12.500
53     9     9     0     0  17.500  17.500   7.500   7.500
54     0     0     0     0  12.500  12.500  12.500  12.500

In [ ]:
df2['flow1']=(((df2['flow1'])/(df2['flow1']+df2['flow4']))*100)/2
df2['flow4']=(((df2['flow3'])/(df2['flow2']+df2['flow3']))*100)/2
df2['flow2']=df2['flow1']
df2['flow3']=df2['flow4']
df2

    pin1  pin2  pin3  pin4   flow1   flow2   flow3   flow4
0      1     1     1     1  25.000  25.000  25.000  25.000
1      2     2     1     1  26.678  26.678  23.322  23.322
2      3     3     1     1  27.098  27.098  22.902  22.902
3      4     4     1     1  27.622  27.622  22.378  22.378
4      5     5     1     1  28.276  28.276  21.724  21.724
5      6     6     1     1  29.096  29.096  20.904  20.904
6      7     7     1     1  30.120  30.120  19.880  19.880
7      8     8     1     1  31.400  31.400  18.600  18.600
8      9     9     1     1  33.000  33.000  17.000  17.000
9      1     1     0     0  26.678  26.678  23.322  23.322
10     2     2     2     2  25.000  25.000  25.000  25.000
11     3     3     2     2  26.678  26.678  23.322  23.322
12     4     4     2     2  27.098  27.098  22.902  22.902
13     5     5     2     2  27.622  27.622  22.378  22.378
14     6     6     2     2  28.276  28.276  21.724  21.724
15     7     7     2     2  29.096  29.096  20.904  20.904
16     8     8     2     2  30.120  30.120  19.880  19.880
17     9     9     2     2  31.400  31.400  18.600  18.600
18     2     2     0     0  27.098  27.098  22.902  22.902
19     3     3     3     3  25.000  25.000  25.000  25.000
20     4     4     3     3  26.678  26.678  23.322  23.322
21     5     5     3     3  27.098  27.098  22.902  22.902
22     6     6     3     3  27.622  27.622  22.378  22.378
23     7     7     3     3  28.276  28.276  21.724  21.724
24     8     8     3     3  29.096  29.096  20.904  20.904
25     9     9     3     3  30.120  30.120  19.880  19.880
26     3     3     0     0  27.622  27.622  22.378  22.378
27     4     4     4     4  25.000  25.000  25.000  25.000
28     5     5     4     4  26.678  26.678  23.322  23.322
29     6     6     4     4  27.098  27.098  22.902  22.902
30     7     7     4     4  27.622  27.622  22.378  22.378
31     8     8     4     4  28.276  28.276  21.724  21.724
32     9     9     4     4  29.096  29.096  20.904  20.904
33     4     4     0     0  28.276  28.276  21.724  21.724
34     5     5     5     5  25.000  25.000  25.000  25.000
35     6     6     5     5  26.678  26.678  23.322  23.322
36     7     7     5     5  27.098  27.098  22.902  22.902
37     8     8     5     5  27.622  27.622  22.378  22.378
38     9     9     5     5  28.276  28.276  21.724  21.724
39     5     5     0     0  29.096  29.096  20.904  20.904
40     6     6     6     6  25.000  25.000  25.000  25.000
41     7     7     6     6  26.678  26.678  23.322  23.322
42     8     8     6     6  27.098  27.098  22.902  22.902
43     9     9     6     6  27.622  27.622  22.378  22.378
44     6     6     0     0  30.120  30.120  19.880  19.880
45     7     7     7     7  25.000  25.000  25.000  25.000
46     8     8     7     7  26.678  26.678  23.322  23.322
47     9     9     7     7  27.098  27.098  22.902  22.902
48     7     7     0     0  31.400  31.400  18.600  18.600
49     8     8     8     8  25.000  25.000  25.000  25.000
50     9     9     8     8  26.678  26.678  23.322  23.322
51     8     8     0     0  33.000  33.000  17.000  17.000
52     9     9     9     9  25.000  25.000  25.000  25.000
53     9     9     0     0  35.000  35.000  15.000  15.000
54     0     0     0     0  25.000  25.000  25.000  25.000

# data for flow 60

In [9]:
pin_positions = list(range(10))
pin_combinations=[position for position in itertools.combinations_with_replacement(pin_positions, 2)]
pin_combinations

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 8),
 (8, 9),
 (9, 9)]

In [ ]:
flow_rate = 60
def flow_division(range_of_difference):
  pos_1= flow_rate*0.7
  pos_2= flow_rate*0.3
  for diff in range(range_of_difference):
    diff_value=(pos_1-pos_2)/10
    pos_1=pos_1-diff_value
    pos_2=pos_2+diff_value
  return (pos_1/24,pos_2/24)

In [ ]:
velocity_lst=[]
flow_lst=[abs]
for pair in pin_combinations:
  if pair[0]>pair[1]:
    range_is=9-pair[0]+pair[1]
    pos_1,pos_2=flow_division(range_is)
    velocity_lst.append([pair[0],pair[0],pair[1],pair[1], pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2, pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2, 
                pos_2+0.25,pos_2-0.3])   
    flow_lst.append([pair[0],pair[0],pair[1],pair[1],x*12,x*12,pos_2*12,pos_2*12])
  elif pair[0]==pair[1]:
    range_is=9
    x,y=flow_division(range_is)
    velocity_lst.append([pair[0],pair[0],pair[1],pair[1],pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2, 
                pos_2+0.25,pos_2-0.3])
    flow_lst.append([pair[0],pair[0],pair[1],pair[1],20,20,20,20])

  else:
    range_is=9-pair[1]+pair[0]
    y,x=flow_division(range_is)
    velocity_lst.append([pair[1],pair[1],pair[0],pair[0], pos_1+0.25,pos_1-0.2,pos_1+0.25,pos_1-0.3,pos_1+0.25,pos_1-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2,pos_2+0.25,pos_2-0.3,pos_2+0.25,pos_2-0.2, 
                pos_1+0.25,pos_1-0.3])                                                  
    flow_lst.append([pair[1],pair[1],pair[0],pair[0],pos_2*12,pos_2*12,pos_1*12,pos_1*12])

In [ ]:
df=pd.DataFrame(velocity_lst)
df.columns=['pin1','pin2','pin3','pin4','v1','v2','v3','v4','v5','v6','v7','v8','v9','v10','v11','v12','v13','v14','v15','v16']
df=df.round(3)
df

    pin1  pin2  pin3  pin4     v1  ...    v12    v13    v14    v15    v16
0      1     1     1     1  1.433  ...  1.017  1.567  1.117  1.433  0.883
1      2     2     1     1  1.416  ...  1.034  1.584  1.134  1.416  0.866
2      3     3     1     1  1.395  ...  1.055  1.605  1.155  1.395  0.845
3      4     4     1     1  1.369  ...  1.081  1.631  1.181  1.369  0.819
4      5     5     1     1  1.336  ...  1.114  1.664  1.214  1.336  0.786
5      6     6     1     1  1.295  ...  1.155  1.705  1.255  1.295  0.745
6      7     7     1     1  1.244  ...  1.206  1.756  1.306  1.244  0.694
7      8     8     1     1  1.180  ...  1.270  1.820  1.370  1.180  0.630
8      9     9     1     1  1.100  ...  1.350  1.900  1.450  1.100  0.550
9      1     1     0     0  1.416  ...  1.034  1.584  1.134  1.416  0.866
10     2     2     2     2  1.433  ...  1.017  1.567  1.117  1.433  0.883
11     3     3     2     2  1.416  ...  1.034  1.584  1.134  1.416  0.866
12     4     4     2     2  1.395  ...  1.055  1.605  1.155  1.395  0.845
13     5     5     2     2  1.369  ...  1.081  1.631  1.181  1.369  0.819
14     6     6     2     2  1.336  ...  1.114  1.664  1.214  1.336  0.786
15     7     7     2     2  1.295  ...  1.155  1.705  1.255  1.295  0.745
16     8     8     2     2  1.244  ...  1.206  1.756  1.306  1.244  0.694
17     9     9     2     2  1.180  ...  1.270  1.820  1.370  1.180  0.630
18     2     2     0     0  1.395  ...  1.055  1.605  1.155  1.395  0.845
19     3     3     3     3  1.433  ...  1.017  1.567  1.117  1.433  0.883
20     4     4     3     3  1.416  ...  1.034  1.584  1.134  1.416  0.866
21     5     5     3     3  1.395  ...  1.055  1.605  1.155  1.395  0.845
22     6     6     3     3  1.369  ...  1.081  1.631  1.181  1.369  0.819
23     7     7     3     3  1.336  ...  1.114  1.664  1.214  1.336  0.786
24     8     8     3     3  1.295  ...  1.155  1.705  1.255  1.295  0.745
25     9     9     3     3  1.244  ...  1.206  1.756  1.306  1.244  0.694
26     3     3     0     0  1.369  ...  1.081  1.631  1.181  1.369  0.819
27     4     4     4     4  1.433  ...  1.017  1.567  1.117  1.433  0.883
28     5     5     4     4  1.416  ...  1.034  1.584  1.134  1.416  0.866
29     6     6     4     4  1.395  ...  1.055  1.605  1.155  1.395  0.845
30     7     7     4     4  1.369  ...  1.081  1.631  1.181  1.369  0.819
31     8     8     4     4  1.336  ...  1.114  1.664  1.214  1.336  0.786
32     9     9     4     4  1.295  ...  1.155  1.705  1.255  1.295  0.745
33     4     4     0     0  1.336  ...  1.114  1.664  1.214  1.336  0.786
34     5     5     5     5  1.433  ...  1.017  1.567  1.117  1.433  0.883
35     6     6     5     5  1.416  ...  1.034  1.584  1.134  1.416  0.866
36     7     7     5     5  1.395  ...  1.055  1.605  1.155  1.395  0.845
37     8     8     5     5  1.369  ...  1.081  1.631  1.181  1.369  0.819
38     9     9     5     5  1.336  ...  1.114  1.664  1.214  1.336  0.786
39     5     5     0     0  1.295  ...  1.155  1.705  1.255  1.295  0.745
40     6     6     6     6  1.433  ...  1.017  1.567  1.117  1.433  0.883
41     7     7     6     6  1.416  ...  1.034  1.584  1.134  1.416  0.866
42     8     8     6     6  1.395  ...  1.055  1.605  1.155  1.395  0.845
43     9     9     6     6  1.369  ...  1.081  1.631  1.181  1.369  0.819
44     6     6     0     0  1.244  ...  1.206  1.756  1.306  1.244  0.694
45     7     7     7     7  1.433  ...  1.017  1.567  1.117  1.433  0.883
46     8     8     7     7  1.416  ...  1.034  1.584  1.134  1.416  0.866
47     9     9     7     7  1.395  ...  1.055  1.605  1.155  1.395  0.845
48     7     7     0     0  1.180  ...  1.270  1.820  1.370  1.180  0.630
49     8     8     8     8  1.433  ...  1.017  1.567  1.117  1.433  0.883
50     9     9     8     8  1.416  ...  1.034  1.584  1.134  1.416  0.866
51     8     8     0     0  1.100  ...  1.350  1.900  1.450  1.100  0.550
52     9     9     9     9  1.433  ...  1.017  1.567  1.117  1.433  0.883
53     9     9     0     0  1.000  ...  1.450  2.000  1.550  1.000  0.450
54     0     0     0     0  1.433  ...  1.017  1.567  1.117  1.433  0.883

[55 rows x 20 columns]

In [ ]:
flow_lst.remove(flow_lst[0])

In [ ]:
df2=pd.DataFrame(flow_lst)
df2=df2.round(3)
df2.columns=['pin1','pin2','pin3','pin4','flow1','flow2','flow3','flow4']
df2

    pin1  pin2  pin3  pin4   flow1   flow2   flow3   flow4
0      1     1     1     1  15.000  15.000  15.000  15.000
1      2     2     1     1  16.007  16.007  13.993  13.993
2      3     3     1     1  16.258  16.258  13.742  13.742
3      4     4     1     1  16.573  16.573  13.427  13.427
4      5     5     1     1  16.966  16.966  13.034  13.034
5      6     6     1     1  17.458  17.458  12.542  12.542
6      7     7     1     1  18.072  18.072  11.928  11.928
7      8     8     1     1  18.840  18.840  11.160  11.160
8      9     9     1     1  19.800  19.800  10.200  10.200
9      1     1     0     0  16.007  16.007  13.993  13.993
10     2     2     2     2  15.000  15.000  15.000  15.000
11     3     3     2     2  16.007  16.007  13.993  13.993
12     4     4     2     2  16.258  16.258  13.742  13.742
13     5     5     2     2  16.573  16.573  13.427  13.427
14     6     6     2     2  16.966  16.966  13.034  13.034
15     7     7     2     2  17.458  17.458  12.542  12.542
16     8     8     2     2  18.072  18.072  11.928  11.928
17     9     9     2     2  18.840  18.840  11.160  11.160
18     2     2     0     0  16.258  16.258  13.742  13.742
19     3     3     3     3  15.000  15.000  15.000  15.000
20     4     4     3     3  16.007  16.007  13.993  13.993
21     5     5     3     3  16.258  16.258  13.742  13.742
22     6     6     3     3  16.573  16.573  13.427  13.427
23     7     7     3     3  16.966  16.966  13.034  13.034
24     8     8     3     3  17.458  17.458  12.542  12.542
25     9     9     3     3  18.072  18.072  11.928  11.928
26     3     3     0     0  16.573  16.573  13.427  13.427
27     4     4     4     4  15.000  15.000  15.000  15.000
28     5     5     4     4  16.007  16.007  13.993  13.993
29     6     6     4     4  16.258  16.258  13.742  13.742
30     7     7     4     4  16.573  16.573  13.427  13.427
31     8     8     4     4  16.966  16.966  13.034  13.034
32     9     9     4     4  17.458  17.458  12.542  12.542
33     4     4     0     0  16.966  16.966  13.034  13.034
34     5     5     5     5  15.000  15.000  15.000  15.000
35     6     6     5     5  16.007  16.007  13.993  13.993
36     7     7     5     5  16.258  16.258  13.742  13.742
37     8     8     5     5  16.573  16.573  13.427  13.427
38     9     9     5     5  16.966  16.966  13.034  13.034
39     5     5     0     0  17.458  17.458  12.542  12.542
40     6     6     6     6  15.000  15.000  15.000  15.000
41     7     7     6     6  16.007  16.007  13.993  13.993
42     8     8     6     6  16.258  16.258  13.742  13.742
43     9     9     6     6  16.573  16.573  13.427  13.427
44     6     6     0     0  18.072  18.072  11.928  11.928
45     7     7     7     7  15.000  15.000  15.000  15.000
46     8     8     7     7  16.007  16.007  13.993  13.993
47     9     9     7     7  16.258  16.258  13.742  13.742
48     7     7     0     0  18.840  18.840  11.160  11.160
49     8     8     8     8  15.000  15.000  15.000  15.000
50     9     9     8     8  16.007  16.007  13.993  13.993
51     8     8     0     0  19.800  19.800  10.200  10.200
52     9     9     9     9  15.000  15.000  15.000  15.000
53     9     9     0     0  21.000  21.000   9.000   9.000
54     0     0     0     0  15.000  15.000  15.000  15.000

In [ ]:
df2['flow1']=(((df2['flow1'])/(df2['flow1']+df2['flow4']))*100)/2
df2['flow4']=(((df2['flow3'])/(df2['flow2']+df2['flow3']))*100)/2
df2['flow2']=df2['flow1']
df2['flow3']=df2['flow4']
df2

    pin1  pin2  pin3  pin4      flow1      flow2      flow3      flow4
0      1     1     1     1  25.000000  25.000000  25.000000  25.000000
1      2     2     1     1  26.678333  26.678333  23.321667  23.321667
2      3     3     1     1  27.096667  27.096667  22.903333  22.903333
3      4     4     1     1  27.621667  27.621667  22.378333  22.378333
4      5     5     1     1  28.276667  28.276667  21.723333  21.723333
5      6     6     1     1  29.096667  29.096667  20.903333  20.903333
6      7     7     1     1  30.120000  30.120000  19.880000  19.880000
7      8     8     1     1  31.400000  31.400000  18.600000  18.600000
8      9     9     1     1  33.000000  33.000000  17.000000  17.000000
9      1     1     0     0  26.678333  26.678333  23.321667  23.321667
10     2     2     2     2  25.000000  25.000000  25.000000  25.000000
11     3     3     2     2  26.678333  26.678333  23.321667  23.321667
12     4     4     2     2  27.096667  27.096667  22.903333  22.903333
13     5     5     2     2  27.621667  27.621667  22.378333  22.378333
14     6     6     2     2  28.276667  28.276667  21.723333  21.723333
15     7     7     2     2  29.096667  29.096667  20.903333  20.903333
16     8     8     2     2  30.120000  30.120000  19.880000  19.880000
17     9     9     2     2  31.400000  31.400000  18.600000  18.600000
18     2     2     0     0  27.096667  27.096667  22.903333  22.903333
19     3     3     3     3  25.000000  25.000000  25.000000  25.000000
20     4     4     3     3  26.678333  26.678333  23.321667  23.321667
21     5     5     3     3  27.096667  27.096667  22.903333  22.903333
22     6     6     3     3  27.621667  27.621667  22.378333  22.378333
23     7     7     3     3  28.276667  28.276667  21.723333  21.723333
24     8     8     3     3  29.096667  29.096667  20.903333  20.903333
25     9     9     3     3  30.120000  30.120000  19.880000  19.880000
26     3     3     0     0  27.621667  27.621667  22.378333  22.378333
27     4     4     4     4  25.000000  25.000000  25.000000  25.000000
28     5     5     4     4  26.678333  26.678333  23.321667  23.321667
29     6     6     4     4  27.096667  27.096667  22.903333  22.903333
30     7     7     4     4  27.621667  27.621667  22.378333  22.378333
31     8     8     4     4  28.276667  28.276667  21.723333  21.723333
32     9     9     4     4  29.096667  29.096667  20.903333  20.903333
33     4     4     0     0  28.276667  28.276667  21.723333  21.723333
34     5     5     5     5  25.000000  25.000000  25.000000  25.000000
35     6     6     5     5  26.678333  26.678333  23.321667  23.321667
36     7     7     5     5  27.096667  27.096667  22.903333  22.903333
37     8     8     5     5  27.621667  27.621667  22.378333  22.378333
38     9     9     5     5  28.276667  28.276667  21.723333  21.723333
39     5     5     0     0  29.096667  29.096667  20.903333  20.903333
40     6     6     6     6  25.000000  25.000000  25.000000  25.000000
41     7     7     6     6  26.678333  26.678333  23.321667  23.321667
42     8     8     6     6  27.096667  27.096667  22.903333  22.903333
43     9     9     6     6  27.621667  27.621667  22.378333  22.378333
44     6     6     0     0  30.120000  30.120000  19.880000  19.880000
45     7     7     7     7  25.000000  25.000000  25.000000  25.000000
46     8     8     7     7  26.678333  26.678333  23.321667  23.321667
47     9     9     7     7  27.096667  27.096667  22.903333  22.903333
48     7     7     0     0  31.400000  31.400000  18.600000  18.600000
49     8     8     8     8  25.000000  25.000000  25.000000  25.000000
50     9     9     8     8  26.678333  26.678333  23.321667  23.321667
51     8     8     0     0  33.000000  33.000000  17.000000  17.000000
52     9     9     9     9  25.000000  25.000000  25.000000  25.000000
53     9     9     0     0  35.000000  35.000000  15.000000  15.000000
54     0     0     0     0  25.000000  25.000000  25.000000  25.000000